spring:
    application: 
       name: ElasticSearchWithSpringBoot
    profiles:      active: dev
    elasticsearch:      rest:        uris: http://localhost:9200

logging:
  level:
    ROOT: INFO
server.port: 9999
