on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
      - feature/*
  pull_request:
      branches: [develop, main]
name: Main Workflow
jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    steps:
    - name: Build	
      uses: qcastel/github-actions-maven/actions/maven@master
      with:
        maven-args: "clean install" 
