on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
      - develop
      - feature/*
  pull_request:
      branches: [develop, main]
name: Main Workflow
jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout a Git repository
      uses: actions/checkout@v2.3.2
    
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
          java-version: 1.11
    - name: Build with Maven
      run: mvn clean verify
      
    - name: perform code coverage result
      uses: codecov/codecov-action@v1
      with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
   
