on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
      - feature/*
  pull_request:
      branches: [develop, main]
name: Main Workflow
jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
          java-version: 1.11
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
